Ajout de la recette des fajitas
diese-french/malaubid pull request #40
Opened 2021-08-20 12:18 UTC by ennael

Hop recette des fajitas avec la photo

2021-08-20 15:12 UTC, ennael commented
Une coquille dans le rendu de la liste des opérations. Un caractère qui doit être mal interprété ?

2021-08-20 15:41 UTC, libussa requested changes
fix pour les caractères bizarres

2021-08-20 15:41 UTC, libussa commented on _recipes/fajitas.md
> +- Etaler chaque boule de manière très fine (1 mm environ) : abaisser la boule étaler au rouleau à pâtisserie, tourner d'1/8, étaler à nouveau au rouleau... jusqu'à faire le tour complet.
c'est du yaml, le `:` est interprété comme le début d'un nouveau champ. Faut juste quoter l'ensemble pour l'échapper.

`- "Etaler chaque boule de manière très fine (1 mm environ) : abaisser la boule étaler au rouleau à pâtisserie, tourner d'1/8, étaler à nouveau au rouleau... jusqu'à faire le tour complet." `

2022-04-20 17:22 UTC, ennael commented on _recipes/fajitas.md
> +- Etaler chaque boule de manière très fine (1 mm environ) : abaisser la boule étaler au rouleau à pâtisserie, tourner d'1/8, étaler à nouveau au rouleau... jusqu'à faire le tour complet.
done

2023-04-25 17:46 UTC, merged